<h1><?= $title; ?></h1>

<p>Hien thi phan duoc render vao<p>
    <a href="#" data-location="/inbox/12">Email Item 12</a>
<br>
    <a href="#" data-location="/inbox/13">Email Item 13</a>
<br>

<script language="JavaScript">

    $('a').click(function (e) {
        e.preventDefault();
        // Detect if pushState is available
        if(history.pushState) {
            history.pushState(null, null, $(this).attr('data-location')); // URL is now /inbox/N
            // showMailItem(); // example function to show email based on link clicked
        }
        return false;
    });

    // Used to detect initial (useless) popstate.
    // If history.state exists, assume browser isn't going to fire initial popstate.
    var popped = ('state' in window.history && window.history.state !== null), initialURL = location.href;

    $(window).bind('popstate', function (event) {
        // Ignore inital popstate that some browsers fire on page load
        var initialPop = !popped && location.href == initialURL
        popped = true
        if (initialPop) return;
        // showMailOverview(); // exmaple function to display all email since the user has click Back.
    });
</script>

