<h1>Welcome to Duc Bui</h1>
<?= $title; ?>
<br>
<?= $title_aaa; ?>

<p>Hien thi phan duoc render vao<p>
<b>Request('site-index/home/child-first') => <?= $child_first; ?></b>
<br>
<b>Request('site-index/home/child-second') => <?= $child_second; ?></b>
<br>

<?= $part_render; ?>

<br>

RENDER lai 1 lan nua trong code template

<?= \TinyFw\Support\Request::run(new \TinyFw\Core\Request('site-index/home/part-render',array('Title duoc truyen vao AGAIN')));?>





