<form action="" name="frmAction" method="POST">

<table width="100%" border="0" cellpadding="1" cellspacing="1">
	<tr>
		<td>Address
		<td><input type="text" name="address" value="" size="40">
	</tr>

	
	
	<tr>
		<td>Content HTML
		<td>
            <input type="file" id="test" multiple>
            <div id="text"></div>
	</tr>
	<tr>
		<td colspan="2"><br><input type="submit" value="Save">&nbsp;<input type="reset" value="Reset"> 
	</tr>		
</table>	

</form>

<script type="text/javascript">
    $('#test').bind('change', function() {
        var files = this.files;
        console.log(files.length);
        var i = 0;
        for(; i < files.length; i++) {
            var filename = files[i].name + "<br />";
            $("#text").append(filename);
        }
    });
</script>

