                <!-- BEGIN Page Title -->
                <div class="page-title">
                    <div>
                        <h1><i class="icon-file-alt"></i> <?php echo $box_title; ?></h1>
                        <h4><?php echo $box_title; ?></h4>
                    </div>
                </div>
                <!-- END Page Title -->

                <!-- BEGIN Main Content -->
                <div class="row-fluid">
                    <div class="span12">

                        <?php echo \App\Helper\AdFunc::showMessage($notify_msg['msg_title'], $notify_msg['msg_code'] ,$notify_msg['msg_content']); ?>
                    
                        <div class="box">
                            <div class="box-title">
                                <h3><i class="icon-file"></i><?php echo $box_action; ?></h3>
                                <div class="box-tool">
                                </div>
                            </div>
                            
                            <div class="box-content">
                            
<form method="POST" id="validation-form" class="form-horizontal form-bordered" action="#">

                                    <div class="control-group">
                                        <label class="control-label" for="textfield4">Username</label>
                                        <div class="controls">
                                            <input type="text" class="input-large" id="username" name="username" placeholder="Username" value="<?php echo h($rowContact["username"]); ?>"
                                                   data-rule-required="true" data-msg-required="Please enter your username" data-msg-email="Please enter your username">
                                        </div>
                                    </div>


                                    <div class="control-group">
                                        <label class="control-label" for="textfield4">Fullname</label>
                                        <div class="controls">
                                            <input type="text" class="input-large"  id="first_name" name="first_name" placeholder="First Name" value="<?php echo h($rowContact["first_name"]); ?>"
                                                   data-rule-required="true" data-msg-required="Please enter your first name">
                                            <input type="text" class="input-large"  id="last_name" name="last_name" placeholder="Last Name" value="<?php echo h($rowContact["last_name"]); ?>"
                                                   data-rule-required="true" data-msg-required="Please enter your last name">
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label" for="textfield4">Email</label>
                                        <div class="controls">
											<input type="text" class="input-xxlarge"  id="email" name="email" placeholder="Email" value="<?php echo h($rowContact["email"]); ?>"
											data-rule-required="true" data-msg-required="Please enter your email" data-rule-email="true" data-msg-email="Please enter a valid email address">
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label" for="textfield4">Address</label>
                                        <div class="controls">
                                            <input type="text" class="input-xxlarge"  id="address" name="address" placeholder="Address" value="<?php echo h($rowContact["address"]); ?>"
                                                   data-rule-required="true" data-msg-required="Please enter your address">
                                        </div>
                                    </div>

                                    
                                    <div class="control-group">
                                        <label class="control-label" for="textfield4">Cellphone</label>
                                        <div class="controls">
											<input type="text" class="input-xxlarge"  id="mobile" name="mobile" placeholder="Cellphone" value="<?php echo h($rowContact["mobile"]); ?>"
											data-rule-required="true" data-msg-required="Please enter your cellphone">                                          	                                            
                                        </div>
                                    </div>
                                                                                                            
                                    <div class="control-group">
                                        <label class="control-label" for="textfield4">Question</label>
                                        <div class="controls">
                                        	<textarea rows="4" class="input-xxlarge" id="question" name="question"
                                        	data-rule-required="true" data-msg-required="Please enter question"><?php echo h($rowContact["question"]); ?></textarea>
                                        </div>
                                    </div>

                                    <div class="control-group">
                                        <label class="control-label" for="textfield4">Subject</label>
                                        <div class="controls">
                                            <input type="text" class="input-xxlarge"  id="subject" name="subject" placeholder="Subject" value="<?php echo h($rowContact["subject"]); ?>"
                                                   data-rule-required="true" data-msg-required="Please enter your subject">
                                        </div>
                                    </div>
                                    
                                    <div class="control-group">
                                        <label class="control-label" for="textfield4">Answer</label>
                                        <div class="controls">
                                        	<textarea rows="10" class="input-xxlarge" id="answer" name="answer"><?php echo h($rowContact["answer"]); ?></textarea>
                                        </div>
                                    </div>                                    
                                
									<div class="control-group">
                                       	<label class="control-label">Reply email to user</label>
                                       	<div class="controls">
                                          	<label class="checkbox">
                                            	<input type="checkbox" id="active" name="active" value="1" <?php echo n($rowContact["active"])==1?'checked':''; ?> >
                                          	</label>
                                       	</div>
                                    </div>                                    
			                                    
                                    <div class="form-actions">
                                       <button type="submit" class="btn btn-primary"><i class="icon-ok"></i> Save</button>
                                       <a href="<?php echo site_url('home/contact/list'); ?>" class="btn">Cancel</a>
                                    </div>                                    
							    
</form>
                            
                            </div>                            
                                
                        </div>
                    </div>
                </div>
                <!-- END Main Content -->
                
                
<script type="text/javascript">
                
$(document).ready(function() {
	$("#validation-form").validate();

});

</script>                
