<!--page specific css styles-->
<link rel="stylesheet" href="<?php echo __TEMPLATE_URL; ?>assets/data-tables/DT_bootstrap.css" />

<div class="content">

    <div class="header">
        <div class="page-title">
            <div>
                <h1><i class="icon-file-alt"></i><?php echo $box_title; ?></h1>
                <h4> <?php echo $box_title; ?></h4>
            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row-fluid">

            <div class="btn-toolbar text-right">
                <a href="<?php echo $add_link; ?>" class="btn btn-primary"><i class="icon-plus"></i> Thêm mới</a>
            </div>

            <!-- BEGIN Main Content -->
            <div class="row-fluid">
                <div class="span12">

                    <?php echo \App\Helper\AdFunc::showMessage($notify_msg['msg_title'], $notify_msg['msg_code'] ,$notify_msg['msg_content']); ?>

                    <div class="box">
                        <div class="box-title">
                            <h3><i class="icon-table"></i><?php echo $box_action; ?></h3>
                            <div class="box-tool">
                            </div>
                        </div>
                        <div class="box-content">
                            <table id="table2" class="table table-striped table-hover fill-head dataTable" aria-describedby="table1_info">
                                <thead>
                                <tr>
                                    <th width="2%" class="nosort"># ID</th>
                                    <th width="20%">Username</th>
                                    <th class="col_link">Fullname</th>
                                    <th>Email</th>
                                    <th>Mobile</th>
                                    <th style="width: 100px;text-align: center" class="col_active">Replied</th>
                                    <th style="width: 70px" class="col_action">Action</th>
                                </tr>
                                </thead>
                                <tbody></tbody>
                            </table>

                        </div>

                    </div>
                </div>
            </div>
            <!-- END Main Content -->


        </div>
    </div>
</div>

<!--page specific plugin scripts-->
<script type="text/javascript" src="<?php echo __TEMPLATE_URL; ?>assets/data-tables/jquery.dataTables.js"></script>
<script type="text/javascript" src="<?php echo __TEMPLATE_URL; ?>assets/data-tables/DT_bootstrap.js"></script>


<script type="text/javascript">
    $(document).ready(function()
    {
        var table = $('#table2').on('processing.dt', function ( e, settings, processing ) {
            $('#processingIndicator').css( 'display', processing ? 'block' : 'none' );

            if(processing)
                console.log('loading ne');
            else
                console.log('loading xong roi');
            // -- su ly processing --
        }).DataTable({
            'aoColumnDefs': [{
                'bSortable': false,
                'aTargets': ['nosort']
            },{
                'bSortable': true,
                "aTargets": ['col_link'], // Column to target
                "mRender": function ( data, type, row ) {
//                    console.log(row[0]);
//                    console.log(data);
                    // 'row' is the row's data object, and 'data' is this column's data
                    // e.g. 'row[0]' is the comic id, and 'data' is the comic title
//                    return '<a href="/comics/' + row[0] + '">' + data + '</a>';
//                    return '';
                    html = '<a title="" href="#">'+data+'</a>';
                    return html;
                }

            },{
                'bSortable': false,
                "aTargets": ['col_action'], // Column to target
                "mRender": function ( data, type, row ) {
                    html = '<a class="btn btn-small btn-gray" title="" href="<?php echo $edit_link; ?>'+row[0]+'"><i class="icon-edit"></i></a>';
                    html += '<a class="btn btn-small btn-danger" title="" href="javascript:confimDelete(\'<?php echo $delete_link; ?>'+row[0]+'\');"><i class="icon-trash"></i></a>';
                    return html;
                }

            },{
                'bSortable': false,
                "sClass": "text-center",
                "aTargets": ['col_active'], // Column to target
                "mRender": function ( data, type, row ) {
                    html = "<a href='#' title='UnActive' class='btn btn-circle btn-gray'><i class='icon-remove-circle'></i></a>";
                    if (data == 1)
                        html = "<a href='#' title='Active' class='btn btn-circle btn-lime'><i class='icon-ok-sign'></i></a>";
                    return html;
                }

            }],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?= site_url('home/contact/list/1'); ?>",

//            "iDisplayLength": 25, // Default show rows
            "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, 'All']],

//            oLanguage: {
//                sProcessing: "<img src='<?//= __IMAGE_URL;?>///loading.gif'>" // Display text processing
//            },

            "processing" : true,


//            "sPaginationType": "bootstrap"
            "sPaginationType": "full_numbers",

//            "paging": true
//            "lengthChange": true,
//            "searching": true,
//            "ordering": false,
//            "info": false,
//            "autoWidth": true

        });

    });
</script>