<!--page specific css styles-->
<link rel="stylesheet" href="<?php echo __TEMPLATE_URL; ?>assets/data-tables/DT_bootstrap.css" />

<div class="content">

	<div class="header">
		<div class="page-title">
            <div>
                <h1><i class="icon-file-alt"></i><?php echo $box_title; ?></h1>
                <h4> <?php echo $box_title; ?></h4>
            </div>
        </div>		
	</div>

	<div class="container-fluid">
		<div class="row-fluid">

			<div class="btn-toolbar text-right">
				<a href="<?php echo $add_link; ?>" class="btn btn-primary"><i class="icon-plus"></i> Thêm mới</a>
			</div>

            <!-- BEGIN Main Content -->
			<div class="row-fluid">
                    <div class="span12">
                    
                        <?php echo \App\Helper\AdFunc::showMessage($notify_msg['msg_title'], $notify_msg['msg_code'] ,$notify_msg['msg_content']); ?>

<!-- 			<div class="alert alert-success fade in">-->
<!-- 				<button data-dismiss="alert" class="close">×</button>-->
<!-- 				<h4>Success!</h4>-->
<!-- 				<ul>-->
<!--                                             <li>List Item 1</li>-->
<!--                                             <li>List Item 2</li>-->
<!--                                             <li>List Item 3</li>-->
<!--                                             <li>List Item 4</li>-->
<!-- 				</ul>-->
<!-- 			</div>-->
<!--			-->
<!-- 			<div class="alert alert-success">-->
<!-- 				<button data-dismiss="alert" class="close">×</button>-->
<!-- 				<strong>Success!</strong> The page has been added.-->
<!-- 			</div>-->

                        <div class="box">
                            <div class="box-title">
                                <h3><i class="icon-table"></i><?php echo $box_action; ?></h3>
                                <div class="box-tool">
                                </div>
                            </div>
                            <div class="box-content">
<!--                                <table class="table table-striped table-hover fill-head">-->
                                    <table id="table2" class="table table-striped table-hover fill-head dataTable" aria-describedby="table1_info">
<!--                                        <table id="table1" class="table table-advance dataTable" aria-describedby="table1_info">-->

                                    <thead>
                                        <tr>
                                            <th width="2%" class="nosort"># ID</th>
                                            <th width="3%"></th>
                                            <th width="20%">Username</th>
                                            <th>Fullname</th>
                                            <th>Email</th>
                                            <th>Mobile</th>
                                            <th style="width: 100px;text-align: center">Replied</th>
                                            <th style="width: 70px" class="nosort">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    
                                    <?php
                                    	foreach ($rsContact as $rowContact) :
                                    ?>
                                    
									<tr>
										<td><?php echo $rowContact['user_id']; ?></td>
										<td></td>
                                        <td>
                                        	<?php echo h($rowContact["username"]); ?>
                                        </td>
                                        <td>
                                            <?php echo h($rowContact["full_name"]); ?>
                                        </td>
                                        <td>
                                            <?php echo h($rowContact["email"]); ?>
                                        </td>
                                        <td>
                                            <?php echo h($rowContact["mobile"]); ?>
                                        </td>

                                        <td style="text-align: center">
                                            <?php if ($rowContact['active'] == 1) : ?>
                                            	<a href='#' title='Active' class='btn btn-circle btn-lime'><i class="icon-ok-sign"></i></a>
                                            <?php else : ?>
                                            	<a href='#' title='UnActive' class='btn btn-circle btn-gray'><i class="icon-remove-circle"></i></a>
                                            <?php endif; ?>                                            
                                        </td>
										<td>	
											<div class="btn-group">
												<a class="btn btn-small btn-gray" title="" href="<?php echo $edit_link.$rowContact['user_id'];?>"><i class="icon-edit"></i></a>
												<a class="btn btn-small btn-danger" title="" href="javascript:confimDelete('<?php echo $delete_link.$rowContact['user_id']; ?>');"><i class="icon-trash"></i></a>
											</div>
										</td>
									</tr>                                    
                                    
                                    <?php
                                    	endforeach; 
                                    ?>
                                        
                                    </tbody>
                                </table>

                                <div class="pagination text-right">
                                    <?php echo $oPaginator->display_pages(); ?>
                                </div>

                            </div>
                            
                        </div>
                    </div>
			</div>
			<!-- END Main Content -->
                			
			
		</div>
	</div>
</div>

<!--page specific plugin scripts-->
<script type="text/javascript" src="<?php echo __TEMPLATE_URL; ?>assets/data-tables/jquery.dataTables.js"></script>
<script type="text/javascript" src="<?php echo __TEMPLATE_URL; ?>assets/data-tables/DT_bootstrap.js"></script>

<script type="text/javascript">
    $(document).ready(function()
    {
        var table = $('#table2').DataTable({
            'aoColumnDefs': [{
                'bSortable': false,
                'aTargets': ['nosort']
            }]
        });

    });
</script>