<h1><?= $title; ?></h1>

<table width="100%" class="table">
	<tr>
		<td width="15%">First Name
		<td><?= h($data['first_name']); ?>
	</tr>
	<tr>
		<td>Last Name
		<td><?= h($data['last_name']); ?>
	</tr>
	<tr>
		<td>Email
		<td><?= h($data['email']); ?>
	</tr>
	<tr>
		<td>Address
		<td><?= h($data['address']); ?>
	</tr>
	<tr>
		<td>Summary
		<td><?= xh($data['summary']); ?>
	</tr>
	<tr>
		<td>Content HTML
		<td>
			<?= html($data['description']); ?>
	</tr>			
</table>	


