<script src="<?php echo __JS_URL; ?>/ckeditor/ckeditor.js"></script>

<h1><?= $title; ?></h1>

<?php if (!empty($errorMessage)) : ?>
    <p class="bg-success"><?= h($errorMessage); ?></p>
<?php endif; ?>


<form action="<?= $link; ?>" name="frmAction" class="form-horizontal" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        <label class="col-sm-2 control-label">First Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="first_name" value="<?= h($data['first_name']); ?>" placeholder="First Name">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Last Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="last_name" value="<?= h($data['last_name']); ?>" placeholder="Last Name">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" name="email" value="<?= h($data['email']); ?>" placeholder="Email">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Address</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="address" value="<?= h($data['address']); ?>" placeholder="Address">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Summary</label>
        <div class="col-sm-10">
            <textarea rows="6" cols="80" id="summary" name="summary"><?= h($data['summary']); ?></textarea>
        </div>
    </div>

    <div class="form-group">
        <label for="inputPassword3" class="col-sm-2 control-label">Content HTML</label>
        <div class="col-sm-10">
            <textarea id="description" name="description" rows="5">
				<?= html($data['description']); ?>
			</textarea>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Sent</button>
            <button type="reset" class="btn btn-default">Reset</button>
        </div>
    </div>
</form>

<script type="text/javascript">
	
	CKEDITOR.replace('description',{
        toolbar : 'Basic_1'
    });

</script>

