<link rel="stylesheet" href="<?= __CSS_URL; ?>/paging.css">

<h1><?= $title; ?></h1>

<a href="<?= $add_link; ?>" >Add Data</a>

<br><br>

<table class="table table-bordered table-hover">
    <thead>
    <tr>
        <th>ID
        <th>First Name
        <th>Last Name
        <th>Email
        <th>Address
        <th>Action
    </tr>
    </thead>

<?php
	foreach ($rs as $row) :
?>
	<tr>
		<td><?= $row['user_id']; ?>
		<td><?= h($row['first_name']); ?>
		<td><?= h($row['last_name']); ?>
		<td><?= h($row['email']); ?>
		<td><?= h($row['address']); ?>
		<td>
			<a href="<?= $view_link . $row['user_id']; ?>">View</a>&nbsp;&nbsp;|&nbsp;
			<a href="<?= $edit_link . $row['user_id']; ?>">Edit</a>&nbsp;&nbsp;|&nbsp;
			<a href="<?= $delete_link . $row['user_id']; ?>">Delete</a>
	</tr>
<?php
	endforeach;
?>

</table>	


<?php
	echo "<br>";
	echo $pages->display_pages(); // Optional call which will display the page numbers after the results.
	echo $pages->display_jump_menu(); // Optional displays the page jump menu
?>