
<!-- BEGIN Page Title -->
<div class="header">
    <div class="page-title">
        <div>
            <h1><i class="icon-cogs"></i> Configuration Systems</h1>
        </div>
    </div>
</div>
<!-- END Page Title -->

<!-- BEGIN Main Content -->

<div class="row-fluid">

    <?php echo \Admin\Helper\AdFunc::showMessage($notify_msg['msg_title'], $notify_msg['msg_code'] ,$notify_msg['msg_content']); ?>

    <div class="box">
        <div class="box-title">
            <h3><i class="icon-cogs"></i>Configs</h3>
        </div>

        <div class="box-content">

            <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
                <?php
                $tab_pos = empty($tab_pos) ? $arrConfigData[0]['id'] : $tab_pos;
                foreach ($arrConfigData as $row) : ?>

                    <li <?php echo ($row['id'] == $tab_pos ? 'class="active"' : ''); ?> >
                        <a href="#tab_id_<?php echo $row['id']?>" data-toggle="tab">
                            <i class="icon-cogs"></i>&nbsp;<?php echo $row['name']?>
                        </a>
                    </li>

                <?php endforeach;?>
            </ul>

            <div id="my-tab-content" class="tab-content" style="overflow: hidden;">

                <?php
                foreach ($arrConfigData as $row) : ?>

                    <div <?php echo ($row['id'] == $tab_pos ? 'class="tab-pane active"' : 'class="tab-pane"'); ?> id="tab_id_<?php echo $row['id']; ?>">

                        <form action="<?php echo $save_link.'/'.$row['id']?>" class="form-horizontal" method="POST">
                            <?php
                            $arrConfigDetails = $row['config_data'];
                            foreach ($arrConfigDetails as $rowConfigDetail) : ?>

                                <div class="control-group">
                                    <label for="textfield4" class="control-label"><?php echo $rowConfigDetail['name']; ?></label>
                                    <div class="controls">
                                        <input type="text" name="<?php echo $rowConfigDetail['code']; ?>" id="<?php echo $rowConfigDetail['code']; ?>" value="<?php echo $rowConfigDetail['value']; ?>" class="input-xxlarge">

                                        <?php if(!empty($rowConfigDetail['note'])) :?>
                                            <blockquote>
                                                <h6><?php echo $rowConfigDetail['note']; ?></h6>
                                            </blockquote>
                                        <?php endif; ?>

                                    </div>
                                </div>

                            <?php endforeach;?>

                            <?php if($_isModify) : ?>
                                <div class="form-actions">
                                    <button type="submit" class="btn btn-primary"><i class="icon-save"></i> Save</button>
                                </div>
                            <?php endif; ?>

                        </form>

                    </div>

                <?php endforeach;?>

            </div>

            <script type="text/javascript">
                jQuery(document).ready(function ($) {
                    $('#tabs').tab();
                });
            </script>

        </div>
    </div>

</div>


<!-- END Main Content -->
