<h1><?= $title; ?></h1>
<h3><?= $sub_title; ?></h3>
<br>

<form action="" name="frmAction" method="POST" enctype="multipart/form-data">

<table width="100%" border="0" cellpadding="1" cellspacing="1">

    <tr>
        <td>Name
        <td><input type="text" name="name" value="" size="40" placeholder="Fullname">
    </tr>
    <tr>
		<td>Email
		<td><input type="text" name="email" value="" size="40" placeholder="Email Address">
	</tr>
    <tr>
        <td colspan="2"><br><input type="submit" value="Sent">&nbsp;<input type="reset" value="Reset">
    </tr>
</table>

</form>

