<!-- Add jQuery library -->
<!--<script type="text/javascript" src="--><?php //echo __JS_URL; ?><!--/jquery-1.8.1.min.js"></script>-->
<script type="text/javascript" src="<?php echo __JS_URL; ?>/ckeditor/ckeditor.js"></script>

<script type="text/javascript"> 								


jQuery(document).ready(function ($) {
	console.debug(CKEDITOR.basePath);
    CKEDITOR.replace( 'email_content', {
		
 		// Similar to example the above, defines a "Basic" toolbar with only one strip containing three buttons.
 		// Note that this setting is composed by "toolbar_" added by the toolbar name, which in this case is called "Basic".
 		// This second part of the setting name can be anything. You must use this name in the CKEDITOR.config.toolbar setting,
 		// so you instruct the editor which toolbar_(name) setting to use.
		
		// customConfig : 'ckeditor/config_basic.js'
		toolbar : 'Basic_1'
		
    });	
    
});

</script>

<h1><?= $sub_title; ?></h1>
<br>

<?php if (!empty($returnSentMail)) : ?>
    <p class="bg-success"><?= $returnSentMail; ?></p>
<?php endif; ?>

<form action="" name="frmAction" class="form-horizontal" method="POST" enctype="multipart/form-data">
    <div class="form-group">
        <label class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" name="email" value="" size="40" placeholder="Email">
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Subject</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="subject" value="" size="80" placeholder="Subject">
        </div>
    </div>

    <div class="form-group">
        <label for="inputPassword3" class="col-sm-2 control-label">Email Content HTML</label>
        <div class="col-sm-10">
            <textarea id="email_content" name="email_content" rows="10" cols="80"></textarea>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Sent</button>
            <button type="reset" class="btn btn-default">Reset</button>
        </div>
    </div>
</form>






