
<!-- BEGIN Page Title -->
<div class="page-title">
    <div>
        <h1><i class="icon-file-alt"></i> Dashboard</h1>
        <h4>Overview, stats, chat and more</h4>
    </div>
</div>
<!-- END Page Title -->

<!-- BEGIN Dashboard Item -->
<div class="row-fluid">

    <div class="span3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row-fluid">
                    <div class="span3">
                        <i class="icon-comments icon-5x"></i>
                    </div>

                    <div class="pull-right span8">
                        <div class="huge text-right">26</div>
                        <div class="huge-sub text-right">New Comments!</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="icon-circle-arrow-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <div class="span3">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row-fluid">
                    <div class="span3">
                        <i class="icon-tasks icon-5x"></i>
                    </div>

                    <div class="pull-right span8">
                        <div class="huge text-right">26</div>
                        <div class="huge-sub text-right">New Tasks!</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="icon-circle-arrow-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <div class="span3">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row-fluid">
                    <div class="span3">
                        <i class="icon-shopping-cart icon-5x"></i>
                    </div>

                    <div class="pull-right span8">
                        <div class="huge text-right">26</div>
                        <div class="huge-sub text-right">New Orders!</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="icon-circle-arrow-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

    <div class="span3">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row-fluid">
                    <div class="span3">
                        <i class="icon-meh icon-5x"></i>
                    </div>

                    <div class="pull-right span8">
                        <div class="huge text-right">26</div>
                        <div class="huge-sub text-right">Support Tickets!</div>
                    </div>
                </div>
            </div>
            <a href="#">
                <div class="panel-footer">
                    <span class="pull-left">View Details</span>
                    <span class="pull-right"><i class="icon-circle-arrow-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>

</div>
<!-- END Dashboard Item -->

<!-- BEGIN Breadcrumb -->
<div id="breadcrumbs">
    <ul class="breadcrumb">
        <li class="active">
            <i class="icon-tasks"></i>
            Module
        </li>
    </ul>
</div>
<!-- END Breadcrumb -->

<!-- BEGIN Main Content -->

<div class="row-fluid">

    <?php
    $i = 1;
    foreach ($menuInfo as $key => $sub_menus) :
        ?>

        <a href="<?php echo site_url($key)?>" class="quick-button span2">
            <i class="<?php echo $sub_menus['icon'];?> icon-4x"></i>
            <p><?php echo $sub_menus['name']; ?></p>
            <!--                        <span class="notification label-xlarge label-success">1.367</span>-->
        </a>

        <?php
        if(($i % 6) == 0 )
            echo "</div><div class='row-fluid'>";
        $i++;
    endforeach;
    ?>
</div>

<br>
<!-- BEGIN Breadcrumb -->
<div id="breadcrumbs">
    <ul class="breadcrumb">
        <li class="active">
            <i class="icon-tasks"></i>
            Functions System
        </li>
    </ul>
</div>
<!-- END Breadcrumb -->

<!-- BEGIN Main Content -->
<div class="row-fluid">
    <?php
    $i = 1;
    foreach ($arrConfigSystemNav['sub_menus'] as $sub_menus) :
        ?>

        <a href="<?php echo site_url($sub_menus['link']); ?>" class="quick-button span2">
            <i class="<?php echo $sub_menus['icon'];?> icon-4x"></i>
            <p><?php echo $sub_menus['name']; ?></p>
            <!--                        <span class="notification label-xlarge label-success">1.367</span>-->
        </a>

        <?php
        if(($i % 6) == 0 )
            echo "</div><div class='row-fluid'>";
        $i++;
    endforeach;
    ?>
</div>


<!-- END Main Content -->