<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Dashboard with Off-canvas Sidebar</title>
    <meta name="generator" content="Bootply" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="<?= __COMPONENT_URL; ?>/bootstrap/bootstrap.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link href="<?= __CSS_URL; ?>/bootstrap_styles.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Profile</a></li>
                <li><a href="#">Help</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <input type="text" class="form-control" placeholder="Search...">
            </form>
        </div>
    </div>
</nav>

<div class="container-fluid">

    <div class="row row-offcanvas row-offcanvas-left">

        <div class="col-sm-3 col-md-2 sidebar-offcanvas" id="sidebar" role="navigation">

            <ul class="nav nav-sidebar">
                <li class="active"><a href="#">Overview</a></li>
                <li><a href="http://bootstrapzero.com" target="_ext">Themes</a></li>
                <li><a href="http://bootstrap.theme.cards" target="_ext">Analytics</a></li>
                <li><a href="https://wrapbootstrap.com?ref=skelly" target="_ext">Export</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li class="active"><a href="">Nav item</a></li>
                <li><a href="">Nav item again</a></li>
                <li><a href="">One more nav</a></li>
                <li><a href="">Another nav item</a></li>
                <li><a href="">More navigation</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="">Nav item again</a></li>
                <li><a href="">One more nav</a></li>
                <li><a href="">Another nav item</a></li>
            </ul>

        </div><!--/span-->

        <div class="col-sm-9 col-md-10 main">

            <?php echo !empty($errorMsg) ? "<div class='error'>{$errorMsg}</div>" : ''; ?>
            <?php echo $main_content; ?>

        </div><!--/row-->
    </div>
</div><!--/.container-->

<footer>
    <p class="pull-right">Powered By <a href="mailto:buivantienduc@yahoo.com">Bui Van Tien Duc</a> ©2016</p>
</footer>

<!-- script references -->
<script src="<?= __COMPONENT_URL?>/jquery/jquery.min.js"></script>
<script src="<?= __COMPONENT_URL?>/bootstrap/bootstrap.min.js"></script>

<script language="JavaScript">
    $(document).ready(function() {
        $('[data-toggle=offcanvas]').click(function() {
            $('.row-offcanvas').toggleClass('active');
        });
    });
</script>


</body>
</html>