<link rel="stylesheet" href="<?= __CSS_URL; ?>/paging.css">


<h1><?= $title; ?></h1>

<select id="bank" name="bank" onchange="location.href = '<?= site_url('google/list-atm-address'); ?>'+'/'+this.value;">
    <option value="0">-- Tất cả --</option>
    <?php foreach ($rsBank as $row) : ?>
        <option value="<?= $row['bank_id']; ?>" <?= $row['bank_id'] == $bankId ? 'selected' : ''; ?>>
            [<?= $row['code']; ?>] <?= $row['name']; ?></option>
    <?php endforeach;?>
</select>

<br><br>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>ID
            <th>Name
            <th>Address
            <th>Lat
            <th>Long
            <th>Action
        </tr>
    </thead>

<?php
	foreach ($rs as $row) :
?>
	<tr>
		<td><?= $row['address_id']; ?>
		<td><?= h($row['name']); ?>
		<td><?= h($row['address']); ?>
		<td><?= h($row['lat']); ?>
		<td><?= h($row['long']); ?>
		<td>&nbsp;
	</tr>
<?php
	endforeach;
?>

</table>

<br>

<h1>Các ngân hàng liên kết</h1>

    <?php foreach ($rsRelationBank as $rowRelationBank) : ?>
        [<?= $rowRelationBank['code']; ?>] <?= $rowRelationBank['name']; ?> <br>

        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>ID
                <th>Name
                <th>Address
                <th>Lat
                <th>Long
                <th>Action
            </tr>
            </thead>

            <?php foreach ($rowRelationBank['listAddress'] as $rowAddress) : ?>
                <tr>
                    <td><?= $rowAddress['address_id']; ?>
                    <td><?= h($rowAddress['name']); ?>
                    <td><?= h($rowAddress['address']); ?>
                    <td><?= h($rowAddress['lat']); ?>
                    <td><?= h($rowAddress['long']); ?>
                    <td>&nbsp;
                </tr>
            <?php endforeach;?>
        </table>
        <br><br>

    <?php endforeach;?>
