<!-- File template -->
<li>
    <a href="/a/flaty-template/img/demo/gallery/1.jpg" rel="prettyPhoto" title="Description of image">
        <div>
            <img src="/a/flaty-template/img/demo/gallery/1_thumb.jpg" alt="">
            <i></i>
        </div>
    </a>
    <div class="gallery-tools">
        <a href="#"><i class="icon-link"></i></a>
        <a href="#"><i class="icon-paper-clip"></i></a>
        <a href="#"><i class="icon-pencil"></i></a>
        <a href="#"><i class="icon-trash"></i></a>
    </div>
</li>





